name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: NoSugarCoffee/hello-world-javascript-action@v1.1
      with:
        who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: mod tidy
      run: go mod tidy
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
